### PR TITLE
Colored Laptops/Flash Drives/Printers + fr_fr.lang

### PR DESCRIPTION
**Pull request by D-prog-55**
Ported to 1.10, made laptops dye-able, tweaked item model

### CODE REVIEW

**Comment by D-prog-55** [comment]
Oh, I also made the dev mode only when in the dev env (so I can play with it right away :smiley:)

**Comment by MrCrayfish** [comment]
I'm not merging this because it will override the 1.11.2 version of the code. A port to 1.10 will be better if done at release of the mod (1.0). Although if you PR the dyeable laptops, that will be good!

**Comment by MrCrayfish** [comment]
I notice the use of metadata for the colour. This won't work as rotation already takes up 4 states, meaning there is only 12 left but there are 16 possible colours. This applies to the laptop and printer. For the USB, it's fine. You will need to implement it into the Tile Entity instead if you want it to work for the laptop and printer.

I would suggest starting the PR again from clean state, due to originally being a 1.10 port. Also please split up the french lang into a separate PR.

**Comment by MrCrayfish** [comment]
Okay, it;s seems I overlooked this PR. It will work, still can you start a clean fresh PR and separate the additions.

**Pull request closed without merging**
