### PR TITLE
give out application instance after registration

### PR DESCRIPTION
**Pull request by lukas2005**
i think that it would be cool if you would have acces to app instance

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Good idea. Might help if you are developing applications to work together

**Comment by lukas2005** [comment]
will you merge ? just asking

**Comment by lukas2005** [comment]
why did u copy pasted the code that i wanted u to merge instead of just merging?

**Comment by MrCrayfish** [comment]
I was in the process of making the mod load on server, and had to refactor the registerApplication method, thus now making the PR conflicting so I just added it myself.

**Pull request closed without merging**
